### ISSUE TITLE
How to access database in rust flutter

### ISSUE THREAD

**Issue by kunjee17** [brickpop/flutter-rust-ffi#17]
Rust has few libraries that allows database access like sqlite and also native storat. Is it possible to do it with rust and access rust function via flutter? 

Basically I want push as much as on Rust side as I'm not that happy with flexibility of dart language. 

BTW thanks for awesome template. :-)

**Comment by brickpop** [comment]
Thank you @kunjee17 :)

In principle there's nothing preventing you to accomplish this use case.
What you need to do is creating a library, importing the Rust dependencies of your choice and then expose your functions so that Dart can call them. 

The part where you should pay most attention would be when passing parameters other than numbers, chars and booleans. Strings need conversion from/to UTF8 pointers and structs can theoretically be mapped on both sides, but I haven't tried them myself.

**Comment by kunjee17** [comment]
Thanks for reply @brickpop . I was specifically asking if I need some native binding to access native api from Rust? 

For example can I use libraries like sqlx, diesel with this approach or it is not possible?

**Comment by brickpop** [comment]
Oh, do you mean accessing still another external library from Rust?

In such case you'd need to bundle the relevant `libsqlite.so` / `libsqlite.a` files (however they look) into the iOS/Android side.
Then, you may need to tell Rust about the external library's signatures ([bindgen](https://github.com/rust-lang/rust-bindgen)) and finally [use them](https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html#using-extern-functions-to-call-external-code)

Hope it helps

**Comment by kunjee17** [comment]
I guess yes. thanks for reply and nice library. I m closing this issue for now.
