### ISSUE TITLE
Pipe Rust standard input/output to Dart

### ISSUE THREAD

**Issue by sengerts** [brickpop/flutter-rust-ffi#19]
Hi,
I am asking myself if I can use this template to call native rust functions and then write to the standard input of the rust
library as well as read from its standard output. Do you know if this is possible? I am asking because I am trying
to integrate a UCI Chess Engine (Stockfish, more specifically its Rust port called Rustfish) into a Flutter App and therefore I need to be able to write to/ read from the standard input/ output to send UCI commands and receive their answers.
I would be very happy if you could help me here.

**Comment by brickpop** [comment]
Hi @sengerts 

Well, any part of a program could get the stdin file descriptor and read from it. The Rust library code you write should be able to do it by itself, same as you would do in a standalone binary.

However, I have no clue on how you plan to launch a mobile app in a way so that you can override its stdin to another program's output. You may be able to do it on desktop apps, but I'm not sure I'm getting your use case right. 

Also, there's no guarantee that Flutter itself won't read anything from stdin itself. You might want to use a local file as a pipe to restrict the inter process communication data to only that related to your use case. 

Not sure if this answers your question
