### ISSUE TITLE
x86_64 arch target

### ISSUE THREAD

**Issue by canewsin** [brickpop/flutter-rust-ffi#3]
Why do you left x86_64,
until now flutter release support arm64, arm arches but in latest they added x86_64 for latest target, so it is better to add x86_64 target also.

**Comment by bugeats** [comment]
I would add that the rustup `armv7-apple-ios` and `armv7s-apple-ios` 32-bit targets have been [deprecated](https://blog.rust-lang.org/2020/01/03/reducing-support-for-32-bit-apple-targets.html) and this tutorial would do good to update as a purely 64-bit project.

**Comment by brickpop** [comment]
`x86_64` wasn't initially added since desktop support wasn't that stable at the time. The downside is that compilation takes even longer, but it can be easily commented out if not needed.

As for `armv7-apple-ios` and `armv7s-apple-ios`, it is true that it is deprecated, but certain Flutter versions (v1.12) still expect this target to be present when compiling the final app. Same as before, it can be easily commented out in the makefile. 

And probably, these two mentions could be added to the Readme itself.

**Comment by brickpop** [comment]
Fixed on https://github.com/brickpop/flutter-rust-ffi/commit/3632616d30244c8bfff198b912d433e1841442cc
